config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'products#index'

  resources :products
  resources :orders do
    collection do
      get :notifications
    end
  end
  resources :cart_products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_products, dependent: :destroy

  scope :stale, -> { where('updated_at < ?', 12.hours.ago) }
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  validates :quantity, numericality: { greater_than_or_equal_to: 1 }
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products, dependent: :destroy
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, numericality: { greater_than_or_equal_to: 1 }

  after_create :update_product_inventory

  def update_product_inventory
    product.update(available: product.available - quantity)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store

  validates :name, presence: true
  validates :available, numericality: { greater_than_or_equal_to: 0 }
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_cart

  private

  def current_cart
    Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Cart.create
    session[:cart_id] = cart.id
    cart
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController
  before_action :set_cart_product, only: [:destroy, :update]

  def update
    @cart_product.update(permitted_params)
  end

  def create
    product = Product.find(params[:cart_product][:product_id])
    cart_product = CartProduct.find_or_initialize_by(product_id: product.id)
    cart_product.quantity = params[:cart_product][:quantity].to_i
    cart_product.persisted? ? cart_product.save : current_cart.cart_products << cart_product
  end

  def destroy
    @cart_product.destroy
  end

  private

  def permitted_params
    params.require(:cart_product).permit(:quantity)
  end

  def set_cart_product
    @cart_product = current_cart.cart_products.find(params[:id])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_admin!

  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    order_service = OrderService.new(current_cart)
    order_service.perform
    flash.now[:success] = 'Order successfully placed'
  rescue StandardError => e
    redirect_to products_path, flash: { error: e.message }
  end

  def index
    @orders = Order.includes(order_products: [:product]).page(params[:page]).per(params[:per_page])
  end

  def notifications
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    query = Product.includes(:store).where(["name LIKE ?","%#{params[:name]}%"])
    query = query.where(store_id: params[:store_id]) if params[:store_id].present?

    @products = query.page(params[:page]).per(params[:per_page])
    @stores = Store.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_alert_class(type)
    case type
    when 'success'
      'success'
    when 'error'
      'danger'
    else
      'info'
    end
  end
end

app/views/application/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= flash_alert_class(type) %> alert-dismissible" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light ps-4 mb-4">
  <div class="container-fluid">
    <%= link_to 'Potloc', root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Products', products_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Cart', 'javascript:void(0);', class: 'nav-link', data: { bs_toggle: "modal", bs_target: "#cartModal" } %>
        </li>

        <li class="nav-item">
          <%= link_to 'Orders', orders_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Order Notifications', notifications_orders_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/cart_products/_cart_product.html.erb
<div class="row">
  <div class="col-md-6">
    <%= cart_product.product.name %>
  </div>

  <div class="col-md-3">
    <%= form_for cart_product, url: cart_product_path(cart_product.id), remote: true, method: :put do |f| %>
        <%= f.number_field :quantity, class: 'form-control', min: 1 %>
        <%= button_tag 'Update', class: 'btn btn-primary mt-2 mb-2' %>
      <% end %>
  </div>

  <div class="col-md-3">
    <%= link_to 'Remove', cart_product_path(cart_product.id), remote: true, method: :delete %>
  </div>
</div>

app/views/cart_products/_index.html.erb
<% current_cart.cart_products.each do |cart_product| %>
  <div id="cart-product-<%= cart_product.id %>" class="border-bottom mb-3">
    <%= render partial: 'cart_products/cart_product', locals: { cart_product: cart_product } %>
  </div>
<% end %>

app/views/cart_products/create.js.erb
$('.cart-products').html('<%= j render partial: 'cart_products/index' %>');
$('#cartModal').modal('show');

app/views/cart_products/destroy.js.erb
$('#cart-product-<%= params[:id] %>').remove();

app/views/cart_products/update.js.erb
$('#cart-product-<%= @cart_product.id %>').html('<%= j render partial: 'cart_products/cart_product', locals: { cart_product: @cart_product } %>');

app/views/carts/_index.html.erb
<div class="modal right fade" id="cartModal" tabindex="" role="dialog" aria-labelledby="cartModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cart</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-body">
        <div class="cart-products">
          <%= render partial: 'cart_products/index' %>
        </div>
      </div>

      <div class="modal-footer border-top-0">
        <%= form_tag orders_path do %>
          <%= button_tag 'Place Order', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Potloc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>

    <div class="container">
      <%= render 'flash' %>
      <%= render partial: 'carts/index' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/create.html.erb
Thanks for your order!

app/views/orders/index.html.erb
<div class="row mt-4">
  <div class="col-md-12 d-flex">
    <h3>Orders</h3>
  </div>
</div>

<table class="table mt-4">
  <thead>
  <tr>
    <th>Products</th>
    <th>Ordered At</th>
  </tr>
  </thead>

  <tbody>
  <% @orders.each do |order| %>
    <tr>
      <td>
        <% order.order_products.each do |order_product| %>
          <div>
            <%= order_product.quantity %>x <%= order_product.product.name %>
          </div>
        <% end %>
      </td>
      <td>
        <%= order.created_at %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/orders/notifications.html.erb
<div class="order--notifications"></div>

<script>
    $(function () {
        OrderNotification.init();
    })
</script>

app/views/products/index.html.erb
<div class="border-bottom mb-5 pb-3">
  <%= form_tag products_path, method: :get do %>
  <div class="row mb-3">
    <div class="col">
      <%= text_field_tag :name, params[:name], class: 'form-control', placeholder: 'Search products...' %>
    </div>

    <div class="col">
      <%= select_tag :store_id, options_for_select(@stores.map { |store| [store.name, store.id] }, selected: params[:store_id]), class: 'form-control', prompt: 'Select Store...' %>
    </div>

    <div class="col">
      <%= select_tag :per_page, options_for_select([['5', '5'], ['10', '10'], ['20', '20']], selected: params[:per_page]), class: 'form-control', include_blank: 'Per page' %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= button_tag 'Search', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>
</div>

<div class="row column-gap-3 row-gap-3">
  <% @products.each do |product| %>
    <div class="product card col-auto" id="product-<%= product.id %>">
      <div class="card-body">
        <h5 class="card-title"><%= product.name %></h5>
        <h6>Store: <%= product.store.name %></h6>
        <h6 class="card-subtitle mb-2 text-muted">Available: <span class="product--available"><%= product.available %></span></h6>

        <%= form_for CartProduct.new, url: cart_products_path, remote: true do |f| %>
          <%= f.hidden_field :product_id, value: product.id %>
          <%= f.number_field :quantity, class: 'form-control', value: 1, min: 1 %>
          <%= button_tag 'Add to cart', class: 'btn btn-primary mt-2' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%= paginate @products %>

<script>
  $(function () {
      Product.init();
  })
</script>